- repo: https://github.com/ambv/black
  rev: master
  hooks:
    - id: black
      language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
    - id: flake8
- repo: local
  hooks:
    - id: wily
      name: wily
      entry: wily diff
      verbose: true
      language: python
      additional_dependencies: [wily]
    - id: bandit
      name: bandit
      entry: bandit -r . -ll
      language: python
      pass_filenames: false
      additional_dependencies: [bandit]
    - id: tests
      name: run tests
      entry: pipenv run test
      language: python
      pass_filenames: false
- repo: https://github.com/prettier/prettier
  rev: master
  hooks:
    - id: prettier
