---
apiVersion: v1
kind: Service
metadata:
  name: contuga-service
spec:
  selector:
    app: contuga
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contuga-deployment
  labels:
    app: contuga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contuga
  template:
    metadata:
      labels:
        app: contuga
    spec:
      containers:
        - name: contuga-test-image
          image: gatsinski/contuga-test-image
          ports:
            - containerPort: 8000
