version: "3"

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    volumes:
      - static-files:/usr/src/app/static
      - media-files:/usr/src/app/media
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static-files:/usr/share/nginx/html/static
      - media-files:/usr/share/nginx/html/media
      - ./nginx:/etc/nginx/conf.d
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  static-files:
  media-files:
  database:
