version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src/app/
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  database:
