# Generated by Django 2.2.15 on 2020-09-22 13:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        )
    ]
