# Generated by Django 2.2.15 on 2020-09-22 10:47
import uuid

from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [("users", "0002_user_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
