# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
           - project-dependencies-{{ checksum "Pipfile.lock" }}
           - project-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv virtualenv
            pipenv install

      - save_cache:
          paths:
            - ~/repo/.venv
          key: project-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run tests
          command: |
            pipenv run ./manage.py test
