version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DJANGO_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-dependencies-{{ checksum "Pipfile.lock" }}
            - python-dependencies-
      - run:
          name: Installing Python dependencies
          command: |
            sudo pip install pipenv
            pipenv sync --dev
      - save_cache:
          paths:
            - ~/repo/.venv
          key: python-dependencies-{{ checksum "Pipfile.lock" }}
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package-lock.json" }}
            - node-dependencies-
      - run:
          name: Installing Node dependencies
          command: |
            npm set cache .npm
            npm ci
      - save_cache:
          paths:
            - .npm
          key: node-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Running tests
          command: |
            sudo apt install sassc -y
            sudo npm i -g uglify-js
            sudo apt install cssmin -y
            pipenv run python manage.py collectstatic --noinput
            pipenv run coverage run manage.py test
            pipenv run coverage report
            pipenv run coverage html
      - run:
          name: Running black
          command: |
            pipenv run black . --check
      - run:
          name: Running flake8
          command: |
            pipenv run flake8 . --statistic --exclude .venv
      - run:
          name: Running isort
          command: |
            pipenv run isort **/*.py --check-only --verbose
      - store_artifacts:
          path: htmlcov
