# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DJANGO_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "Pipfile.lock" }}
            - project-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv sync --dev

      - save_cache:
          paths:
            - ~/repo/.venv
          key: project-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run tests
          command: |
            pipenv run coverage run manage.py test
            pipenv run coverage report
            pipenv run coverage html

      - run:
          name: Run black
          command: |
            pipenv run black . --check

      - run:
          name: Run flake8
          command: |
            pipenv run flake8 . --statistic --exclude .venv
      - run:
          name: Run isort
          command: |
            pipenv run isort **/*.py --check-only --verbose
      - store_artifacts:
          path: htmlcov
