# Generated by Django 3.1.4 on 2020-12-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("accounts", "0003_account_owner"),
        ("categories", "0002_category_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="users.user",
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_usages",
                        to="accounts.account",
                        verbose_name="Default account",
                    ),
                ),
                (
                    "default_expenditures_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_usages_for_expenditures",
                        to="categories.category",
                        verbose_name="Default category for expenditures",
                    ),
                ),
                (
                    "default_incomes_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_usages_for_incomes",
                        to="categories.category",
                        verbose_name="Default category for incomes",
                    ),
                ),
            ],
            options={
                "verbose_name": "User settings",
                "verbose_name_plural": "All user settings",
                "ordering": ["user"],
            },
        )
    ]
