# Generated by Django 2.2.9 on 2020-02-02 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("accounts", "0002_account_is_active"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_usages",
                        to="accounts.Account",
                        verbose_name="Default account",
                    ),
                ),
                (
                    "default_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_usages",
                        to="categories.Category",
                        verbose_name="Default category",
                    ),
                ),
            ],
            options={
                "verbose_name": "User settings",
                "verbose_name_plural": "All user settings",
                "ordering": ["user"],
            },
        )
    ]
