# Generated by Django 2.2.9 on 2020-02-02 19:45

from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_model("users", "User")
    Settings = apps.get_model("settings", "Settings")
    for user in User.objects.all():
        Settings.objects.create(user=user)


def backward(apps, schema_editor):
    Settings = apps.get_model("settings", "Settings")
    Settings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("settings", "0001_initial")]

    operations = [migrations.RunPython(forward, backward)]
