# Generated by Django 2.2.11 on 2020-04-07 19:52

from django.db import migrations
from django.db.models import F


def forward(apps, schema_editor):
    Settings = apps.get_model("settings", "Settings")
    Settings.objects.update(
        default_incomes_category=F("default_category"),
        default_expenditures_category=F("default_category"),
    )


class Migration(migrations.Migration):

    dependencies = [("settings", "0003_default_incomes_and_expenditures_categories")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
