# Generated by Django 2.2.11 on 2020-04-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("settings", "0004_copy_default_categories")]

    operations = [
        migrations.RemoveField(model_name="settings", name="default_category")
    ]
