# Generated by Django 2.2.15 on 2020-09-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_remove_settings_default_category"),
        ("categories", "0005_auto_20200922_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="default_expenditures_category_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_usages_for_expenditures_uuid",
                to="categories.Category",
                to_field="uuid",
                verbose_name="Default category for expenditures",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="default_incomes_category_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_usages_for_incomes_uuid",
                to="categories.Category",
                to_field="uuid",
                verbose_name="Default category for incomes",
            ),
        ),
    ]
