# Generated by Django 2.2.15 on 2020-09-22 10:47
from django.db import migrations


def forward(apps, schema_editor):
    Settings = apps.get_model("settings", "Settings")

    for settings in Settings.objects.all():
        if settings.default_expenditures_category:
            settings.default_expenditures_category_uuid_id = (
                settings.default_expenditures_category.uuid
            )

        if settings.default_incomes_category:
            settings.default_incomes_category_uuid_id = (
                settings.default_incomes_category.uuid
            )

        settings.save()


class Migration(migrations.Migration):

    dependencies = [("settings", "0006_auto_20200922_1532")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
