# Generated by Django 2.2.15 on 2020-09-22 12:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("settings", "0007_auto_20200922_1532")]

    operations = [
        migrations.RemoveField(
            model_name="settings", name="default_expenditures_category"
        ),
        migrations.RemoveField(model_name="settings", name="default_incomes_category"),
        migrations.RenameField(
            model_name="settings",
            old_name="default_expenditures_category_uuid",
            new_name="default_expenditures_category",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="default_incomes_category_uuid",
            new_name="default_incomes_category",
        ),
    ]
