# Generated by Django 2.2.15 on 2020-09-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("settings", "0008_auto_20200922_1538")]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="default_expenditures_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_usages_for_expenditures",
                to="categories.Category",
                verbose_name="Default category for expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="default_incomes_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_usages_for_incomes",
                to="categories.Category",
                verbose_name="Default category for incomes",
            ),
        ),
    ]
