# Generated by Django 2.2.15 on 2020-09-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20200922_1612"),
        ("settings", "0009_auto_20200922_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="default_account_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_usages_uuid",
                to="accounts.Account",
                to_field="uuid",
                verbose_name="Default account",
            ),
        )
    ]
