# Generated by Django 2.2.15 on 2020-09-22 10:47
from django.db import migrations


def forward(apps, schema_editor):
    Settings = apps.get_model("settings", "Settings")

    for settings in Settings.objects.all():
        if settings.default_account:
            settings.default_account_uuid_id = settings.default_account.uuid
            settings.save()


class Migration(migrations.Migration):

    dependencies = [("settings", "0010_settings_default_account_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
