# Generated by Django 2.2.15 on 2020-09-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0012_auto_20200922_1622"),
        ("accounts", "0015_auto_20200922_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="default_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_usages",
                to="accounts.Account",
                verbose_name="Default account",
            ),
        )
    ]
