# Generated by Django 2.2.9 on 2020-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        )
    ]
