# Generated by Django 3.1.4 on 2020-12-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("accounts", "0001_initial"), ("currencies", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="currencies.currency",
            ),
        )
    ]
