# Generated by Django 2.2.11 on 2020-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_account_is_active")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=22, verbose_name="Balance"
            ),
        )
    ]
