# Generated by Django 2.2.11 on 2020-03-29 09:58

from django.db import migrations
from django.db.models import Sum, Q


def calculate_balance(account):
    expenditures, incomes = account.transactions.aggregate(
        expenditures=Sum("amount", filter=Q(type="expenditure")),
        incomes=Sum("amount", filter=Q(type="income")),
    ).values()

    incomes = incomes or 0
    expenditures = expenditures or 0
    return incomes - expenditures


def forward(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")

    for account in Account.objects.all():
        account.balance = calculate_balance(account)
        account.save(update_fields=["balance"])


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_account_balance")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
