# Generated by Django 2.2.15 on 2020-09-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("accounts", "0004_update_balances"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency_foreign_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="currencies.Currency",
            ),
        )
    ]
