# Generated by Django 2.2.15 on 2020-09-11 19:24

from django.db import migrations

# At the time when this migration was executed,
# all users were Bulgarian.
CURRENCIES = {
    "BGN": "Български лев",
    "EUR": "Евро",
    "USD": "Щатски долар",
    "GBP": "Британски паунд",
    "CHF": "Швейцарски франк",
    "RUB": "Руска рубла",
    "CNY": "Китайски юан",
}


def forward(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Currency = apps.get_model("currencies", "Currency")

    for account in Account.objects.all():
        currency = Currency.objects.get_or_create(
            code=account.currency,
            author=account.owner,
            defaults={"name": CURRENCIES[account.currency]},
        )[0]

        account.currency_foreign_key = currency
        account.save()


def backward(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")

    for account in Account.objects.all():
        account.currency = account.currency_foreign_key.code
        account.currency_foreign_key.delete()
        account.save()


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_account_currency_foreign_key")]

    operations = [migrations.RunPython(forward, backward)]
