# Generated by Django 2.2.15 on 2020-09-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0004_auto_20200922_1502"),
        ("accounts", "0007_auto_20200912_1159"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_uuid",
                to="currencies.Currency",
                to_field="uuid",
            ),
        )
    ]
