# Generated by Django 2.2.15 on 2020-09-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0009_fill_currency_uuid")]

    operations = [
        migrations.RemoveField(model_name="account", name="currency"),
        migrations.RenameField(
            model_name="account", old_name="currency_uuid", new_name="currency"
        ),
    ]
