# Generated by Django 2.2.15 on 2020-09-22 13:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0011_auto_20200922_1505")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        )
    ]
