# Generated by Django 2.2.15 on 2020-09-22 13:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20200922_1612"),
        # Removing id foreign keys before removing the field
        ("settings", "0012_auto_20200922_1622"),
        ("transactions", "0010_auto_20200922_1614"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="id"),
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
