# Generated by Django 2.2.15 on 2020-09-22 10:47
import uuid

from django.db import migrations


def forward(apps, schema_editor):
    Category = apps.get_model("categories", "Category")

    for category in Category.objects.all():
        category.uuid = uuid.uuid4()
        category.save()


class Migration(migrations.Migration):

    dependencies = [("categories", "0003_category_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
