# Generated by Django 3.1.4 on 2020-12-30 21:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                (
                    "code",
                    models.CharField(blank=True, max_length=3, verbose_name="ISO code"),
                ),
                (
                    "nominal",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Nominal"),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ["name", "code", "created_at"],
            },
        )
    ]
