# Generated by Django 2.2.15 on 2020-09-22 10:47
import uuid

from django.db import migrations


def forward(apps, schema_editor):
    Currency = apps.get_model("currencies", "Currency")

    for currency in Currency.objects.all():
        currency.uuid = uuid.uuid4()
        currency.save()


class Migration(migrations.Migration):

    dependencies = [("currencies", "0002_currency_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
