# Generated by Django 2.2.15 on 2020-09-22 12:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("currencies", "0003_fill_uuid")]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, null=True, unique=True
            ),
        )
    ]
