# Generated by Django 2.1.8 on 2019-04-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transactions", "0002_auto_20190317_1936"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.Account",
                verbose_name="Account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="categories.Category",
                verbose_name="Category",
            ),
        ),
    ]
