# Generated by Django 3.1.4 on 2021-01-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("transactions", "0002_auto_20201230_2309")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="expenditure_counterpart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_counterpart",
                to="transactions.transaction",
                verbose_name="Expenditure counterpart",
            ),
        )
    ]
