# Generated by Django 2.2.15 on 2020-09-22 10:47
from django.db import migrations


def forward(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")

    for transaction in Transaction.objects.all():
        if transaction.category:
            transaction.category_uuid_id = transaction.category.uuid
            transaction.save()


class Migration(migrations.Migration):

    dependencies = [("transactions", "0004_transaction_category_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
