# Generated by Django 2.2.15 on 2020-09-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("transactions", "0005_auto_20200922_1532")]

    operations = [
        migrations.RemoveField(model_name="transaction", name="category"),
        migrations.RenameField(
            model_name="transaction", old_name="category_uuid", new_name="category"
        ),
    ]
