# Generated by Django 2.2.15 on 2020-09-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transactions", "0006_auto_20200922_1543")]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="categories.Category",
                verbose_name="Category",
            ),
        )
    ]
