# Generated by Django 2.2.15 on 2020-09-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20200922_1612"),
        ("transactions", "0007_auto_20200922_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_uuid",
                to="accounts.Account",
                to_field="uuid",
                verbose_name="Account",
            ),
        )
    ]
