# Generated by Django 2.2.15 on 2020-09-22 10:47
from django.db import migrations


def forward(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")

    for transaction in Transaction.objects.all():
        transaction.account_uuid_id = transaction.account.uuid
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [("transactions", "0008_transaction_account_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
