# Generated by Django 2.2.15 on 2020-09-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("transactions", "0009_auto_20200922_1613")]

    operations = [
        migrations.RemoveField(model_name="transaction", name="account"),
        migrations.RenameField(
            model_name="transaction", old_name="account_uuid", new_name="account"
        ),
    ]
