# Generated by Django 2.2.15 on 2020-09-22 13:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transactions", "0012_auto_20200922_1640")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        )
    ]
