# Generated by Django 2.2.15 on 2020-09-22 10:47
import uuid

from django.db import migrations


def forward(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")

    for transaction in Transaction.objects.all():
        transaction.uuid = uuid.uuid4()
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [("transactions", "0013_transaction_uuid")]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
