# Generated by Django 2.2.15 on 2020-09-22 13:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transactions", "0014_fill_uuid")]

    operations = [
        migrations.RemoveField(model_name="transaction", name="id"),
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
